package main

func main() {
	// recover()，用于终止错误处理流程。
}
